version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:   # Add networks section to specify the custom network
      - rms-network

networks:     # Define the custom network
  rms-network:
    driver: bridge
